name: kite
description: A lightweight Flutter CLI tool to create projects, scaffold architecture, generate boilerplate code, and manage dependencies for faster Flutter development.
version: 0.0.1-dev.1

homepage: https://orkitt.dev
repository: https://github.com/orkitt/kite
issue_tracker: https://github.com/orkitt/kite/issues

screenshots:
  - description: 'Orkitt Kite Client'
    path: screenshots/icon.png
topics:
  - cli
  - scaffold
  - generator
  - boilerplate
  - developer-tools

environment:
  sdk: ^3.1.0

dependencies:
  path: ^1.9.0
  args: ^2.4.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6