import 'dart:io';

import 'package:path/path.dart' as p;

import '../generation/conflict_strategy.dart';
import '../generation/file_writer.dart';
import '../generation/generation_plan.dart';
import '../generation/generation_result.dart';
import '../generation/project_manifest.dart';
import '../naming/name_converter.dart';
import '../project/kite_config.dart';
import '../templates/template_manifest.dart';
import '../version.dart';

final class GeneratedRouterWriter {
  const GeneratedRouterWriter({
    this.fileWriter = const FileWriter(),
    this.manifestStore = const ProjectManifestStore(),
  });

  static const String generatedHeader = '''// -----------------------------------------------------------------------------
// GENERATED BY KITE.
//
// Do not edit this file manually.
// Update routing through Kite CLI or kite.yaml.
//
// https://kite.orkitt.dev
// -----------------------------------------------------------------------------
''';

  final FileWriter fileWriter;
  final ProjectManifestStore manifestStore;

  Future<GenerationResult> writeGeneratedRoutes({
    required Directory projectRoot,
    required KiteConfig config,
    required KiteRoutingConfig routing,
    required bool dryRun,
  }) async {
    final files = buildGeneratedFiles(config: config, routing: routing);
    final plan = GenerationPlan(
      templateId: 'routing.generated',
      templateVersion: kiteCliVersion,
      variables: <String, Object?>{
        'routing': <String, Object?>{
          'shell': routing.shell.enabled,
          'branches': routing.shell.branches.map((item) => item.name).toList(),
          'routes': routing.routes.map((item) => item.path).toList(),
        },
      },
      files: files.entries
          .map(
            (entry) => PlannedFile(
              relativePath: entry.key,
              content: entry.value,
              templatePath: 'routing.generated:${entry.key}',
              upgradePolicy: TemplateUpgradePolicy.replace,
            ),
          )
          .toList(growable: false),
    );

    final result = await fileWriter.write(
      root: projectRoot,
      plan: plan,
      conflictStrategy: ConflictStrategy.overwrite,
      dryRun: dryRun,
    );
    if (!dryRun) {
      await manifestStore.record(
        root: projectRoot,
        generationId: 'routing.generated',
        plan: plan,
        result: result,
      );
      for (final file in result.files) {
        if (file.checksum == null) {
          continue;
        }
        await manifestStore.updateManagedChecksum(
          root: projectRoot,
          relativePath: file.relativePath,
          checksum: file.checksum!,
        );
      }
    }
    return result;
  }

  Future<GenerationResult> writeShell({
    required Directory projectRoot,
    required String sourceDirectory,
    required KiteShellConfig shell,
    required ConflictStrategy conflictStrategy,
    required bool dryRun,
  }) async {
    if (!shell.enabled || shell.branches.isEmpty) {
      return const GenerationResult(<GeneratedFileResult>[]);
    }
    final relativePath = p.posix.join(
      _portable(sourceDirectory),
      'app',
      'router',
      'app_shell.dart',
    );
    final plan = GenerationPlan(
      templateId: 'routing.shell',
      templateVersion: kiteCliVersion,
      variables: <String, Object?>{
        'branches': shell.branches.map((item) => item.name).toList(),
      },
      files: <PlannedFile>[
        PlannedFile(
          relativePath: relativePath,
          content: buildAppShell(shell),
          templatePath: 'routing.shell:app_shell.dart',
          upgradePolicy: TemplateUpgradePolicy.preserve,
        ),
      ],
    );
    final result = await fileWriter.write(
      root: projectRoot,
      plan: plan,
      conflictStrategy: conflictStrategy,
      dryRun: dryRun,
    );
    if (!dryRun) {
      await manifestStore.record(
        root: projectRoot,
        generationId: 'routing.shell',
        plan: plan,
        result: result,
      );
    }
    return result;
  }

  Map<String, String> buildGeneratedFiles({
    required KiteConfig config,
    required KiteRoutingConfig routing,
  }) {
    if (routing.shell.enabled && routing.shell.branches.isEmpty) {
      throw StateError(
        'routing.shell.enabled is true but no shell branches are configured.',
      );
    }

    final source = _portable(config.sourceDirectory);
    final base = p.posix.join(source, 'app', 'router', 'generated');
    final files = <String, String>{};

    for (final route in routing.routes) {
      final feature = NameConverter(route.feature);
      files[p.posix.join(base, 'features', '${feature.snakeCase}_route.dart')] =
          _buildFeatureRoute(config, route, feature);
    }

    files[p.posix.join(base, 'root_routes.dart')] = _buildRootRoutes(routing);

    if (routing.shell.enabled) {
      for (final branch in routing.shell.branches) {
        final branchName = NameConverter(branch.name);
        files[p.posix.join(
          base,
          'branches',
          '${branchName.snakeCase}_branch.dart',
        )] = _buildBranch(routing, branch, branchName);
      }
    }

    files[p.posix.join(base, 'generated_routes.dart')] =
        _buildGeneratedRoutes(routing);
    return Map<String, String>.unmodifiable(files);
  }

  String buildAppShell(KiteShellConfig shell) {
    final navigationDestinations = shell.branches
        .map((branch) {
          final label = NameConverter(branch.name).pascalCase;
          return '''          NavigationDestination(
            icon: Icon(Icons.circle_outlined),
            selectedIcon: Icon(Icons.circle),
            label: '$label',
          ),''';
        })
        .join('\n');
    final railDestinations = shell.branches
        .map((branch) {
          final label = NameConverter(branch.name).pascalCase;
          return '''                NavigationRailDestination(
                  icon: Icon(Icons.circle_outlined),
                  selectedIcon: Icon(Icons.circle),
                  label: Text('$label'),
                ),''';
        })
        .join('\n');

    return '''import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

class AppShell extends StatelessWidget {
  const AppShell({required this.navigationShell, super.key});

  final StatefulNavigationShell navigationShell;

  void _selectBranch(int index) {
    navigationShell.goBranch(
      index,
      initialLocation: index == navigationShell.currentIndex,
    );
  }

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        if (constraints.maxWidth >= 720) {
          return Scaffold(
            body: Row(
              children: <Widget>[
                NavigationRail(
                  selectedIndex: navigationShell.currentIndex,
                  onDestinationSelected: _selectBranch,
                  destinations: const <NavigationRailDestination>[
$railDestinations
                  ],
                ),
                Expanded(child: navigationShell),
              ],
            ),
          );
        }

        return Scaffold(
          body: navigationShell,
          bottomNavigationBar: NavigationBar(
            selectedIndex: navigationShell.currentIndex,
            onDestinationSelected: _selectBranch,
            destinations: const <NavigationDestination>[
$navigationDestinations
            ],
          ),
        );
      },
    );
  }
}
''';
  }

  String _buildFeatureRoute(
    KiteConfig config,
    KiteRouteConfig route,
    NameConverter feature,
  ) {
    final featureRoutePath = p.posix.join(
      _portable(config.sourceDirectory),
      'app',
      'router',
      'generated',
      'features',
      '${feature.snakeCase}_route.dart',
    );
    final screenPath = switch (route.architecture) {
      'clean' => p.posix.join(
        _portable(config.featureDirectory),
        feature.snakeCase,
        'presentation',
        'screens',
        '${feature.snakeCase}_screen.dart',
      ),
      'mvc' => p.posix.join(
        _portable(config.featureDirectory),
        feature.snakeCase,
        'views',
        'screens',
        '${feature.snakeCase}_screen.dart',
      ),
      _ => throw StateError(
        'Unsupported route architecture `${route.architecture}` for '
        '`${route.feature}`.',
      ),
    };
    var importPath = p.posix.relative(
      screenPath,
      from: p.posix.dirname(featureRoutePath),
    );
    if (!importPath.startsWith('.')) {
      importPath = './$importPath';
    }

    return '''$generatedHeader
import 'package:go_router/go_router.dart';

import '$importPath';

GoRoute ${feature.camelCase}Route({required String path}) {
  return GoRoute(
    path: path,
    builder: (context, state) => const ${feature.pascalCase}Screen(),
  );
}
''';
  }

  String _buildRootRoutes(KiteRoutingConfig routing) {
    final routes = routing.routes
        .where((route) => route.branch == 'root')
        .toList(growable: false);
    final imports = routes
        .map((route) {
          final feature = NameConverter(route.feature);
          return "import 'features/${feature.snakeCase}_route.dart';";
        })
        .join('\n');
    final entries = routes
        .map((route) {
          final feature = NameConverter(route.feature);
          return '  ${feature.camelCase}Route(path: AppRoutes.${feature.camelCase}),';
        })
        .join('\n');

    return '''$generatedHeader
import 'package:go_router/go_router.dart';

import '../app_routes.dart';
${imports.isEmpty ? '' : '$imports\n'}
final List<RouteBase> rootRoutes = <RouteBase>[
${entries.isEmpty ? '' : '$entries\n'}];
''';
  }

  String _buildBranch(
    KiteRoutingConfig routing,
    KiteShellBranchConfig branch,
    NameConverter branchName,
  ) {
    final routes = routing.routes
        .where((route) => route.branch == branch.name)
        .toList(growable: false);
    final imports = routes
        .map((route) {
          final feature = NameConverter(route.feature);
          return "import '../features/${feature.snakeCase}_route.dart';";
        })
        .join('\n');
    final children = routes
        .map((route) {
          final feature = NameConverter(route.feature);
          final routeConstant = '${branchName.camelCase}${feature.pascalCase}';
          return '''        ${feature.camelCase}Route(
          path: _relativeChildPath(
            AppRoutes.${branchName.camelCase},
            AppRoutes.$routeConstant,
          ),
        ),''';
        })
        .join('\n');

    return '''$generatedHeader
import 'package:go_router/go_router.dart';

import '../../../../shared/widgets/app_startup_view.dart';
import '../../app_routes.dart';
${imports.isEmpty ? '' : '$imports\n'}
final StatefulShellBranch ${branchName.camelCase}Branch = StatefulShellBranch(
  routes: <RouteBase>[
    GoRoute(
      path: AppRoutes.${branchName.camelCase},
      builder: (context, state) => const AppStartupView(),
      routes: <RouteBase>[
${children.isEmpty ? '' : '$children\n'}      ],
    ),
  ],
);

String _relativeChildPath(String parentPath, String childPath) {
  if (parentPath == '/') {
    return childPath.substring(1);
  }
  return childPath.substring(parentPath.length + 1);
}
''';
  }

  String _buildGeneratedRoutes(KiteRoutingConfig routing) {
    if (!routing.shell.enabled) {
      return '''$generatedHeader
import 'package:go_router/go_router.dart';

import '../../../shared/widgets/app_startup_view.dart';
import '../app_routes.dart';
import 'root_routes.dart';

final String generatedInitialLocation = AppRoutes.home;

final List<RouteBase> generatedRoutes = <RouteBase>[
  GoRoute(
    path: AppRoutes.home,
    builder: (context, state) => const AppStartupView(),
  ),
  ...rootRoutes,
];
''';
    }

    final branches = routing.shell.branches;
    final imports = branches
        .map((branch) {
          final name = NameConverter(branch.name);
          return "import 'branches/${name.snakeCase}_branch.dart';";
        })
        .join('\n');
    final branchEntries = branches
        .map((branch) {
          final name = NameConverter(branch.name);
          return '      ${name.camelCase}Branch,';
        })
        .join('\n');
    final firstBranch = NameConverter(branches.first.name);

    return '''$generatedHeader
import 'package:go_router/go_router.dart';

import '../app_routes.dart';
import '../app_shell.dart';
$imports
import 'root_routes.dart';

final String generatedInitialLocation = AppRoutes.${firstBranch.camelCase};

final List<RouteBase> generatedRoutes = <RouteBase>[
  StatefulShellRoute.indexedStack(
    builder: (context, state, navigationShell) {
      return AppShell(navigationShell: navigationShell);
    },
    branches: <StatefulShellBranch>[
$branchEntries
    ],
  ),
  ...rootRoutes,
];
''';
  }

  String _portable(String path) => path.replaceAll('\\', '/');
}
